[platformio]
default_envs = bench_detector, bench_controller

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

; =========================================
; OUR BENCH / DEVELOPMENT HARDWARE
; =========================================

[env:bench_detector]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.35/platform-espressif32.zip
framework = arduino
board = esp32-c6-devkitc-1
build_flags =
    -D ROLE_DETECTOR
    -D BOARD_ESP32_C6

[env:bench_controller]
board = esp32dev
build_flags =
    -D ROLE_CONTROLLER
    -D BOARD_WROOM32E

; =========================================
; END-USER HARDWARE
; Seeed Studio XIAO ESP32-C3
; =========================================

[env:xiao_c3_detector]
board = seeed_xiao_esp32c3
build_flags =
    -D ROLE_DETECTOR
    -D BOARD_XIAO_C3

[env:xiao_c3_controller]
board = seeed_xiao_esp32c3
build_flags =
    -D ROLE_CONTROLLER
    -D BOARD_XIAO_C3
